title: Put your title here
description: Put the description here
theme: jekyll-theme-minimal
google_analytics: #Here goes your GA id

owner_name: Put your name here
permalink: /:title
future: false

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
